#+LATEX_COMPILER: pdflatex
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:
#+LATEX_HEADER: \usepackage[a4paper,bindingoffset=0.2in,left=1in,right=1in,top=1in,bottom=1in,footskip=.25in]{geometry}
#+LATEX_HEADER_EXTRA:
#+TITLE: Smart Health and Safety Compliance Management for Construction Enterprises
#+SUBTITLE:
#+DESCRIPTION:
#+KEYWORDS:
#+DATE: \today


* Proposal summary
In 2013, The New Zealand Government set a target to reduce work-related fatalities and serious injuries by at least 25% in seven years. Worksafe, the country's primary workplace health and safety (H&S) regulator, has used three work-related indicators to measure the progress over this period. The latest official data released by Stats NZ indicated that despite the initial decline two out of these three indicators have bounced back in the past few years (Figure 1), where the construction industry recorded the highest number of incidents related to indicator 2 and the second highest in indicator 3.  

A review of the current safety management conducts in the construction industry shows them taking stock in individual reporting and filing colossal paperwork. It makes their output prone to human errors originated either from mistakes or from slips and lapses of memory. These issues together with the potential physical loss of information present a serious flaw in the system. Simultaneously, companies are forced to bid with the lowest profit margins to survive in their high competitive environment. Therefore, it is a high priority for every construction company to take up an H&S compliance management solution that could balance costs, risks and governance. This proposal aims to complete one step towards sustaining a system that combines the power of machine learning and image processing to "smartify" the risk identification and reporting at the construction sites. Image processing enables the analysis of the safety compliance based on images from the job site. Machine learning applies artificial intelligence (AI) to automate learning and to improve from experience without being explicitly programmed. The proposed system provides an accessible and inexpensive solutions operable from the ordinary devices such as the mobile phones with a minimum/ no training period.

* Development background

This research presents a novel idea in the field of construction H&S that was initiated by two early-carrier researchers of the Built Environment Engineering department at AUT. It was elaborated further by taking to an external industrial project manager. The team completed an initial feasibility assessment by testing the capability of the combination of Image processing and machine learning in a particular case (figure 2).
Next, the idea was presented to BRANZ, a major player of research, testing, and consulting in the New Zealand building industry at two steps. In the first step, a senior scientist of the company investigated the idea, who brought it to the attention of their investment manager. The second step involved rationalising the definition of a research project based on the proposed idea for the funders. As a result, the team was encouraged to apply for an out of cycle funding subject to providing a proof of concept in the industrial context. Accordingly, a senior scholar in the computer science department at AUT was invited and joined in mid-2019. Since then, the team has worked on presenting the idea to the potential stakeholders form the industry. 
* Expected outcomes
This study researches into a niche area, leading to contextual benchmarks for smartification of the compliance management in the construction sector. It can provide useful pointers and information with a contextual transferability of results to the peer domains.

* Project milestones
** Project kick-off
   - December 1st, 2020
** Project delivery
   - Febrary 15th, 2021

-          Required resources (equipment)
-          Schedule of the project delivery: The project period is December 1st, 2020 to February 15th, 2021
-          Estimated total number of hours for delivery of each phase of the project
-          Hourly rate ($/hrs)
* Cost
** Resources

** Effort

| Item | Description          | hours | rate | cost |
|------+----------------------+-------+------+------|
|      | Issue tracker set-up |     2 |      |      |
|      | Data collection      |    16 |      |      |
|      |                      |       |      |      |
